- name: Create source directory
  file:
    path: "{{ repo_dir }}/openstack"
    state: directory

- name: Clone Cinder repos
  git:
    repo: "https://git.openstack.org/openstack/{{ item }}"
    dest: "{{ repo_dir }}/openstack/{{ item }}"
  with_items: "{{ cinder_repos }}"

- name: Fixing permissions
  # Issue doing this with file so using chown
  command: "chown -R {{ ansible_user_id }}:{{ ansible_user_gid }} {{ repo_dir }}"
  args:
    warn: false
