- name: "Create source directory {{ repo_dir }}"
  file:
    path: "{{ repo_dir }}/openstack"
    state: directory

- name: Clone Cinder repos
  git:
    repo: "https://git.openstack.org/openstack/{{ item }}"
    dest: "{{ repo_dir }}/openstack/{{ item }}"
  with_items: "{{ cinder_repos }}"

- name: Fixing permissions
  # Issue doing this with file so using chown
  command: "chown -R {{ ansible_user_id }}:{{ ansible_user_gid }} {{ repo_dir }}"
  args:
    warn: false
  when: ansible_user_id != "root"

- name: Moving instructions
  debug:
    msg:
      - "!!!!!!!!!!!!!!!!"
      - "Unable to get correct user path!"
      - ""
      - "Unable to determine your actual user name."
      - "You will need to execute the following to finalize setup:"
      - ""
      - "    sudo mv /root/src ~/"
      - "    chown -R [user]:[group] ~/src"
      - "!!!!!!!!!!!!!!!!"
  when: ansible_user_id == "root"
